### ISSUE TITLE
Shopper USER STORY: Add Items to Bag

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/vintage_drums#11]
## User Story

As a shopper, I want to add items to my bag so that I can continue shopping and purchase all item together.

### Acceptance Criteria:

- [ ] 	1 “Add to Bag” button adds the product to the bag.
- [ ] 	2 Bag icon updates with the number of items
- [ ] 3 Total cost displayed
