### ISSUE TITLE
Shopper USER STORY: Add Customisation if buying full drum kit.

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/vintage_drums#17]
## User Story

As a shopper, I want to be able to add customisation to bass drum if buying the full kit so that I can my initials on the bass drum. 

### Acceptance Criteria:

- [ ] 1 Add customise option for drum kits only
- [ ] 2 This will be on the drum kit product description.
- [ ] 3 It will be toggle on off. It will increase the price, 
- [ ] 4 Ask for initials and show other samples
