### ISSUE TITLE
shopper USER STORY: Sorting Products

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/vintage_drums#35]
## User Story

As a shopper I want to sort the products so that I can see the products by rating or price

### Acceptance Criteria:

- [x] 	1 Select a sort option, price and rating
- [x] 	2 Display the results for the search
- [x] 	3 The sorting will be applied to current category or search friendly name
